---
title: "logPPR as a function of tAI, 5'UTR, CDS, 3'UTR deltaG, and their interactions"
date: "02/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE, warning=FALSE}
library(car)
library(lme4)
library(reshape2)
```


#### logPPR ~ tAI + 5'UTR deltaG + CDS deltaG + 3'UTR deltaG + all pairwise interactions{.tabset .tabset-dropdown}
##### Menu
##### Define the response variable, logPPR.
```{r response_variable}
response <- read.csv("C:/Users/anastacia/Desktop/n_PPR_1312_d.csv")
dataset <- melt(response, id.vars = "gene", variable.name = "strain", value.name = "PPR")
dataset$logPPR <- log(dataset$PPR)
```

##### Read in 5'UTR deltaG Data
```{r a}
explanatory0 <- read.csv('C:/Users/anastacia/Desktop/UT5_struc_frac_30C_G_1312.csv')
explanatory0 <- melt(explanatory0, id.vars = "gene", variable.name = "strain", value.name = "UTR5")
dataset$UTR5 = explanatory0$UTR5/1000/100 #multiply resulting slope by 10 to get units of 1/(Mcal per mol)
```

##### Read in CDS deltaG Data
```{r b}
explanatory1 <- read.csv('C:/Users/anastacia/Desktop/CDS_struc_frac_30C_G_1312.csv')
explanatory1 <- melt(explanatory1, id.vars = "gene", variable.name = "strain", value.name = "CDS")
dataset$CDS = explanatory1$CDS/1000/1000 #do not multiply resulting slope by anything; it will be in Mcal/mol already
```

##### Read in 3'UTR deltaG Data
```{r c}
explanatory2 <- read.csv('C:/Users/anastacia/Desktop/UT3_struc_frac_30C_G_1312.csv')
explanatory2 <- melt(explanatory2, id.vars = "gene", variable.name = "strain", value.name = "UTR3")
dataset$UTR3 = explanatory2$UTR3/1000/100 #multiply resulting slope by 10 to get units of 1/(Mcal per mol)
```

##### Read in tAI Data
```{r d}
explanatory3 <- read.csv('C:/Users/anastacia/Desktop/tAI_1312_YRC_diff_d.csv')
explanatory3 <- melt(explanatory3, id.vars = "gene", variable.name = "strain", value.name = "tAI")
dataset$tAI = explanatory3$tAI
```

##### Summary Results of Mixed Model
``` {r F1}
lmm0 <- lmer(logPPR ~ tAI + CDS + UTR5 + UTR3 + CDS:UTR5 + CDS:UTR3 + UTR5:UTR3 + tAI:CDS + tAI:UTR5 + tAI:UTR3 + tAI:CDS:UTR5 + tAI:CDS:UTR3 + tAI:UTR5:UTR3 + (1+tAI|gene) + (1+CDS|gene) + (1|gene) + (0+UTR3|gene), data=dataset, REML = FALSE, control = lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=1e5)))
summary(lmm0)
```

##### 95% Confidence Intervals
``` {r F1confint}
confint(lmm0, parm="tAI", level=0.95)
confint(lmm0, parm="UTR5", level=0.95)
confint(lmm0, parm="CDS", level=0.95)
confint(lmm0, parm="UTR3", level=0.95)
confint(lmm0, parm="tAI:UTR5", level=0.95)
confint(lmm0, parm="tAI:CDS", level=0.95)
confint(lmm0, parm="tAI:UTR3", level=0.95)
confint(lmm0, parm="UTR5:CDS", level=0.95)
confint(lmm0, parm="CDS:UTR3", level=0.95)
confint(lmm0, parm="UTR5:UTR3", level=0.95)
confint(lmm0, parm="tAI:UTR5:CDS", level=0.95)
confint(lmm0, parm="tAI:CDS:UTR3", level=0.95)
confint(lmm0, parm="tAI:UTR5:UTR3", level=0.95)
```