---
title: "logPPR as a function of ensemble deltaG (synonymous SNPs only)"
date: "10/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE, warning=FALSE}
library(car)
library(lme4)
library(reshape2)
```


#### logPPR ~ deltaG {.tabset .tabset-dropdown}
##### Menu
##### Define the response variable, logPPR.
```{r response_variable0}
response <- read.csv("C:/Users/anastacia/Desktop/n_PPR_176_d.csv")
dataset  <- melt(response, id.vars = "gene", variable.name = "strain", value.name = "PPR")
dataset$logPPR <- log(dataset$PPR)
```

##### Read in deltaG Data
```{r FdelG}
explanatory1 <- read.csv('C:/Users/anastacia/Desktop/ensemble_fe_176_30C.csv')
explanatory1 <- melt(explanatory1, id.vars = "gene", variable.name = "strain", value.name = "ensembleG")
dataset$ensembleG = explanatory1$ensembleG/10000 #divide resulting slope by 10 to get units of 1/(Mcal per mol)
```

##### Summary Results of Mixed Model
``` {r F1}
lmm0 <- lmer(logPPR ~ ensembleG + (1+ensembleG|gene), data=dataset, REML = FALSE, control = lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=1e5)))
summary(lmm0)
```

##### 95% Confidence Interval of Mixed Model
``` {r F1confint}
confint(lmm0, parm="ensembleG", level=0.95)
```

##### Fixed Effects Slope Significance Results
``` {r F2}
lmm00 <- lmer(logPPR ~ (1+ensembleG|gene), data=dataset, REML = FALSE, control = lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=1e5)))
anova(lmm0, lmm00)
```
