---
title: "sqrtPPR as a function of tAI, ensemble deltaG, and their interaction"
date: "3/15/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE, warning=FALSE}
library(car)
library(lme4)
library(reshape2)
```


#### sqrtPPR ~ tAI + deltaG + tAI:deltaG {.tabset .tabset-dropdown}
##### Menu
##### Define the response variable, sqrtPPR.
```{r response_variable0}
response <- read.csv("n_PPR_1447_d.csv")
dataset  <- melt(response, id.vars = "gene", variable.name = "strain", value.name = "PPR")
dataset$sqrtPPR <- sqrt(dataset$PPR)
```
##### Read in tAI Data
```{r Ftai}
explanatory0 <- read.csv('tAI_1447_YRC_diff_d.csv')
explanatory0 <- melt(explanatory0, id.vars = "gene", variable.name = "strain", value.name = "tAI")
dataset$tAI = explanatory0$tAI
```

##### Read in deltaG Data
```{r FdelG}
explanatory1 <- read.csv('ensemble_fe_1447_30C.csv')
explanatory1 <- melt(explanatory1, id.vars = "gene", variable.name = "strain", value.name = "ensembleG")
dataset$ensembleG = explanatory1$ensembleG/1000
```

#include median protein abundance for each gene
```{r pa}
explanatory2 <- read.csv('PA_medians_1447.csv')
explanatory2 <- melt(explanatory2, id.vars = "gene", variable.name = "strain", value.name = "medianPA")
dataset$medianPA = explanatory2$medianPA/10000
head(dataset)
```

##### Summary Results of Mixed Model
``` {r F1}
lmm0 <- lmer(sqrtPPR ~ tAI + ensembleG + tAI:ensembleG + (0+ensembleG|gene) + (0+tAI:ensembleG|gene) + (0+tAI|medianPA) + (0+tAI:ensembleG|medianPA) + (1|medianPA), data=dataset, REML = FALSE, control = lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=1e5)))
summary(lmm0)
```

##### 95% Confidence Interval of Mixed Model
``` {r F1confint}
confint(lmm0, parm="tAI", level=0.95)
confint(lmm0, parm="ensembleG", level=0.95)
confint(lmm0, parm="tAI:ensembleG", level=0.95)
```

##### Fixed Effects Slope Significance Results
``` {r F2}
lmm00 <- lmer(sqrtPPR ~ (0+ensembleG|gene) + (0+tAI:ensembleG|gene) + (0+tAI|medianPA) + (0+tAI:ensembleG|medianPA) + (1|medianPA), data=dataset, REML = FALSE, control = lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=1e5)))
fullcomp<-anova(lmm0, lmm00)
fullcomp
```

##### p-value
``` {r F2p}
fullcomp[2,8]
```
